FROM --platform=linux/amd64 node:lts AS build-stage
LABEL org.opencontainers.image.source=https://github.com/HarshitDoshi/sio-tha/siowebclient
WORKDIR /application
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM --platform=linux/amd64 nginx:stable-alpine AS server-stage
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /application/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]