FROM --platform=linux/amd64 python:3.12 as build
LABEL org.opencontainers.image.source=https://github.com/HarshitDoshi/sio-tha/siowebserver
WORKDIR /application
RUN pip install --no-cache-dir --upgrade pip setuptools wheel poetry
COPY . /application
RUN poetry install --no-root
CMD ["poetry", "run", "fastapi", "run", "main.py", "--port", "8000"]