services:
  application_programming_interfaces:
    container_name: "APIs"
    image: ghcr.io/harshitdoshi/sio-tha/siowebserver:siowebserver
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      DATABASE_TYPE: postgresql
      DATABASE_DRIVER: psycopg
      DATABASE_USER: staplesuperuser
      DATABASE_PASSWORD: staplesuperusersecret
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: staple
    depends_on:
      - database
