services:
  database_client:
    container_name: "DatabaseClient"
    image: dpage/pgadmin4:latest
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: superuser@staple.io
      PGADMIN_DEFAULT_PASSWORD: staplesuperusersecret
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - database
