services:
  web_client:
    container_name: "WebClient"
    image: ghcr.io/harshitdoshi/sio-tha/siowebclient:siowebclient
    ports:
      - 8080:80
    environment:
      - NODE_ENV=production
    depends_on:
      - application_programming_interfaces
