services:
  web_server:
    container_name: "WebServer"
    image: nginx:latest
    expose:
      - 80
    ports:
      - 8008:80
    environment:
      - NGINX_HOST=tha.staple.io
      - NGINX_PORT=80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      # - application_programming_interfaces
      - database
