apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: application-programming-interfaces
  name: application-programming-interfaces
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: application-programming-interfaces
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: application-programming-interfaces
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - env:
            - name: DATABASE_DRIVER
              value: psycopg
            - name: DATABASE_HOST
              value: database
            - name: DATABASE_NAME
              value: staple
            - name: DATABASE_PASSWORD
              value: staplesuperusersecret
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_TYPE
              value: postgresql
            - name: DATABASE_USER
              value: staplesuperuser
          image: ghcr.io/harshitdoshi/sio-tha/siowebserver:siowebserver
          name: apis
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
