apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-persistentvolume
spec:
  capacity:
    storage: 1024Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/postgres
