apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJTR0Z5YzJocGRFUnZjMmhwT21kb2NGOXdhSHBrY0VnM01HUlFWR1ZhVDJkeU1qbDVWVk5uYTFsS1ZtSlpZV1l5TjBnMFJqVT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
